//! The v0 wire messages and the Envelope codec.
//!
//! [`Envelope`] and every message type it can carry are generated at build time from the
//! frozen `proto/appricot/v0/wire.proto` (see `build.rs`) and re-exported flat here: build a
//! message, wrap it in [`Envelope`] with [`Body`], and hand it to the codec. The codec adds
//! the limits table of [`crate::limits`] and the v0 wire rules as a gate on both directions:
//!
//! - [`encode_envelope`] refuses to emit a message with a field over its cap, or with a value
//!   v0 does not define, so a violation can never leave this side.
//! - [`decode_envelope`] refuses input over [`MAX_MESSAGE_BYTES`] before parsing anything.
//!   It then runs a pre-scan over the raw bytes that allocates nothing: every length and
//!   every count is compared with its cap there, at cap + 1, before prost builds a single
//!   element or copies a single string. Only then does prost parse, and the same validation
//!   as on encode runs over the decoded values.
//! - [`validate_envelope`] runs the validation on its own, for callers holding an
//!   already-decoded [`Envelope`].
//!
//! The accepted set is the TypeScript mirror's, exactly (v0.md §1): an unknown field inside a
//! known message is skipped; an envelope with no body, an unknown body or a second body is
//! refused; an enum value v0 does not define is refused; a varint over 32 bits on a known
//! field is refused; a singular field that appears twice is refused.
//!
//! Encoding is deterministic: fields are emitted in field-number order, so
//! `encode(decode(bytes))` of a well-formed message is byte-identical to `bytes`. The
//! shared test vectors in `testdata/vectors.json` (regenerated by `tests/vectors.rs`) pin
//! those bytes, and the bytes both codecs must refuse, for the TypeScript mirror.
//!
//! Every string that arrives through these messages is untrusted text: a client renders it
//! as text, never as markup or a navigation (docs/adr/0003). The codec bounds it; what a
//! caller does with it is the caller's rule.

/// The generated `appricot.v0` package, straight from prost.
///
/// The `include!`d code is generated (`build.rs`), so the allows below exempt only that
/// module from the workspace's `missing_docs`, `unused_qualifications` and clippy gates;
/// every hand-written item in this crate still carries them in full.
pub mod appricot {
    /// The v0 package generated from `proto/appricot/v0/wire.proto`.
    #[allow(missing_docs)]
    #[allow(unused_qualifications)]
    #[allow(clippy::all)]
    pub mod v0 {
        include!(concat!(env!("OUT_DIR"), "/appricot.v0.rs"));
    }
}

pub use appricot::v0::envelope::Body;
pub use appricot::v0::*;

use std::fmt;

use prost::Message;

use crate::limits::{
    MAX_APP_ID_BYTES, MAX_BYE_TEXT_BYTES, MAX_CLIENT_NAME_BYTES, MAX_CLIPBOARD_BYTES,
    MAX_CODECS_OFFERED, MAX_CURSOR_BYTES, MAX_CURSOR_HEIGHT, MAX_CURSOR_WIDTH,
    MAX_ERROR_TEXT_BYTES, MAX_KEY_CODE_BYTES, MAX_MESSAGE_BYTES, MAX_POINTER_AXIS_STEPS,
    MAX_SESSION_ID_BYTES, MAX_SURFACE_HEIGHT, MAX_SURFACE_WIDTH, MAX_TILE_BYTES, MAX_TILE_HEIGHT,
    MAX_TILE_WIDTH, MAX_TILES_PER_FRAME, MAX_TITLE_BYTES, MAX_TOKEN_BYTES,
};
use crate::prescan::{self, Refusal};

/// Why [`encode_envelope`] refused a message.
///
/// The field path names the first rule the message broke, as a dotted path from the message
/// root (`"surface_new.title"`); the names are the same on decode and on encode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EncodeError {
    /// A field broke a cap in the limits table, or a value rule beside it (a zero scale, a
    /// zero tile codec, an empty key code, a configure serial of 0, cursor bytes that are not
    /// width * height * 4); nothing was emitted.
    LimitViolation {
        /// The offending field, as a dotted path from the message root.
        field: &'static str,
    },
    /// A field carries a value v0 does not define, an unknown enum value, or the envelope has
    /// no body; nothing was emitted.
    ProtocolViolation {
        /// The offending field, as a dotted path from the message root.
        field: &'static str,
    },
}

impl fmt::Display for EncodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::LimitViolation { field } => write!(f, "field {field} breaks the limits table"),
            Self::ProtocolViolation { field } => write!(f, "field {field} breaks the v0 rules"),
        }
    }
}

impl std::error::Error for EncodeError {}

/// Why [`decode_envelope`] refused a message.
///
/// A field path names the first rule the message broke, exactly as in [`EncodeError`].
#[derive(Debug, Clone)]
pub enum DecodeError {
    /// The input is longer than [`MAX_MESSAGE_BYTES`]; refused before any parsing.
    TooLarge,
    /// A length or a count broke a cap in the limits table, or a decoded value broke a value
    /// rule beside it (see [`EncodeError::LimitViolation`]). A cap is checked on the raw
    /// bytes, before anything is allocated for the field.
    LimitViolation {
        /// The offending field, as a dotted path from the message root.
        field: &'static str,
    },
    /// The envelope names no message this side knows: it has no body at all, or a field
    /// number no v0 message has. v0.md §1: the receiver closes without a reply.
    UnknownMessage,
    /// The bytes break the v0 grammar: they are truncated, a length runs past its message, a
    /// known field has the wrong wire type or a varint over 32 bits, a field number is 0, a
    /// group or an undefined wire type appears, a string is not UTF-8, a field that is not
    /// repeated appears twice, the envelope carries a second body, or an enum field carries a
    /// value v0 does not define.
    ProtocolViolation {
        /// The offending field, as a dotted path from the message root, or the message.
        field: &'static str,
    },
    /// prost refused bytes the pre-scan passed. The pre-scan checks everything prost does, so
    /// this is not expected; it is kept so that no prost error is ever swallowed. prost is not
    /// part of this crate's public API.
    Decode(prost::DecodeError),
}

impl From<prost::DecodeError> for DecodeError {
    fn from(error: prost::DecodeError) -> Self {
        Self::Decode(error)
    }
}

impl fmt::Display for DecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::TooLarge => write!(f, "over {MAX_MESSAGE_BYTES} bytes"),
            Self::LimitViolation { field } => write!(f, "field {field} breaks the limits table"),
            Self::UnknownMessage => write!(f, "the envelope names no v0 message"),
            Self::ProtocolViolation { field } => write!(f, "field {field} breaks the v0 rules"),
            Self::Decode(e) => write!(f, "not an Envelope: {e}"),
        }
    }
}

impl std::error::Error for DecodeError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Decode(e) => Some(e),
            _ => None,
        }
    }
}

/// A rule [`check`] found broken.
enum Violation {
    /// A cap or a value rule: [`DecodeError::LimitViolation`].
    Limit(&'static str),
    /// A value v0 does not define: [`DecodeError::ProtocolViolation`].
    Protocol(&'static str),
    /// No body at all.
    NoBody,
}

impl From<Violation> for DecodeError {
    fn from(violation: Violation) -> Self {
        match violation {
            Violation::Limit(field) => Self::LimitViolation { field },
            Violation::Protocol(field) => Self::ProtocolViolation { field },
            Violation::NoBody => Self::UnknownMessage,
        }
    }
}

impl From<Violation> for EncodeError {
    fn from(violation: Violation) -> Self {
        match violation {
            Violation::Limit(field) => Self::LimitViolation { field },
            Violation::Protocol(field) => Self::ProtocolViolation { field },
            Violation::NoBody => Self::ProtocolViolation { field: "body" },
        }
    }
}

impl From<Refusal> for DecodeError {
    fn from(refusal: Refusal) -> Self {
        match refusal {
            Refusal::Limit(field) => Self::LimitViolation { field },
            Refusal::Grammar(field) => Self::ProtocolViolation { field },
            Refusal::UnknownMessage => Self::UnknownMessage,
        }
    }
}

/// Checks `envelope` against every rule one message can break: the rows of the limits table,
/// the value rules beside them, and the closed enum sets.
///
/// Returns the first broken rule as [`DecodeError::LimitViolation`] or
/// [`DecodeError::ProtocolViolation`]. An `Envelope` whose oneof names no body is
/// [`DecodeError::UnknownMessage`]: v0 has no body-less envelope.
///
/// Rows that bound living session state ([`crate::limits::MAX_SURFACES`] and friends) are not
/// decidable from one message and are the streamer's to check.
pub fn validate_envelope(envelope: &Envelope) -> Result<(), DecodeError> {
    check(envelope).map_err(DecodeError::from)
}

/// Encodes one `Envelope` as the bytes of one WebSocket binary message.
///
/// Fails with [`EncodeError::LimitViolation`] when any field breaks the limits table or a
/// value rule, and with [`EncodeError::ProtocolViolation`] on an enum value v0 does not
/// define or a missing body. The check runs before a byte is emitted, so this side can never
/// send a violation.
pub fn encode_envelope(envelope: &Envelope) -> Result<Vec<u8>, EncodeError> {
    check(envelope).map_err(EncodeError::from)?;
    Ok(envelope.encode_to_vec())
}

/// Decodes the bytes of one WebSocket binary message into an `Envelope`.
///
/// Fails with [`DecodeError::TooLarge`] when the input is over [`MAX_MESSAGE_BYTES`], before
/// a single byte is parsed. Then the pre-scan, which allocates nothing, fails with
/// [`DecodeError::LimitViolation`] on a length or a count over its cap, with
/// [`DecodeError::UnknownMessage`] when there is no known body, and with
/// [`DecodeError::ProtocolViolation`] on bytes that break the grammar. Only then does prost
/// parse, so what it allocates is bounded by the limits table; the decoded values then pass
/// the same checks as on encode. Never panics on any input.
pub fn decode_envelope(bytes: &[u8]) -> Result<Envelope, DecodeError> {
    if bytes.len() > MAX_MESSAGE_BYTES {
        return Err(DecodeError::TooLarge);
    }
    prescan::envelope(bytes)?;
    let envelope = Envelope::decode(bytes)?;
    check(&envelope)?;
    Ok(envelope)
}

/// The width/height field names a size violation can be reported under, kept as pairs so a
/// `cap_size` call stays one line in [`check`].
const SURFACE_NEW_SIZE: (&str, &str) = ("surface_new.size.width", "surface_new.size.height");
/// The size of the positioner of a [`Body::SurfaceNew`] popup.
const POSITIONER_SIZE: (&str, &str) = (
    "surface_new.positioner.size.width",
    "surface_new.positioner.size.height",
);
/// The size of a [`Body::ResizeAsk`].
const RESIZE_ASK_SIZE: (&str, &str) = ("resize_ask.size.width", "resize_ask.size.height");
/// The size of a [`Body::Configure`].
const CONFIGURE_SIZE: (&str, &str) = ("configure.size.width", "configure.size.height");
/// The size of a [`Body::ConfigureAck`].
const CONFIGURE_ACK_SIZE: (&str, &str) = ("configure_ack.size.width", "configure_ack.size.height");

/// The limits table, the value rules and the closed enums as one predicate: the error names
/// the first broken rule.
///
/// One arm per wire message; a message with nothing to check has its arm spelled out anyway,
/// so a new message added to the `.proto` fails this match and forces a decision here.
fn check(envelope: &Envelope) -> Result<(), Violation> {
    let Some(body) = envelope.body.as_ref() else {
        return Err(Violation::NoBody);
    };
    match body {
        Body::Hello(m) => {
            cap_str(&m.client_name, MAX_CLIENT_NAME_BYTES, "hello.client_name")?;
            cap_bytes(&m.stream_token, MAX_TOKEN_BYTES, "hello.stream_token")?;
            cap_count(m.codecs.len(), MAX_CODECS_OFFERED, "hello.codecs")?;
        }
        Body::HelloReply(m) => {
            cap_str(
                &m.session_id,
                MAX_SESSION_ID_BYTES,
                "hello_reply.session_id",
            )?;
            cap_count(m.codecs.len(), MAX_CODECS_OFFERED, "hello_reply.codecs")?;
        }
        Body::Bye(m) => {
            closed::<ByeReason>(m.reason, "bye.reason")?;
            cap_str(&m.text, MAX_BYE_TEXT_BYTES, "bye.text")?;
        }
        Body::ServerError(m) => cap_str(&m.text, MAX_ERROR_TEXT_BYTES, "server_error.text")?,
        Body::SurfaceNew(m) => check_surface_new(m)?,
        Body::SurfaceGone(m) => closed::<SurfaceGoneReason>(m.reason, "surface_gone.reason")?,
        Body::SurfaceMetadata(m) => {
            if let Some(title) = m.title.as_ref() {
                cap_str(title, MAX_TITLE_BYTES, "surface_metadata.title")?;
            }
            if let Some(app_id) = m.app_id.as_ref() {
                cap_str(app_id, MAX_APP_ID_BYTES, "surface_metadata.app_id")?;
            }
            if m.scale_120ths == Some(0) {
                return Err(Violation::Limit("surface_metadata.scale_120ths"));
            }
        }
        Body::ResizeAsk(m) => cap_size(m.size.as_ref(), RESIZE_ASK_SIZE)?,
        Body::Configure(m) => {
            // Serial 0 is never a host serial: it marks the server's ConfigureAck for a size
            // change the host did not configure (v0.md §4.2).
            if m.serial == 0 {
                return Err(Violation::Limit("configure.serial"));
            }
            cap_size(m.size.as_ref(), CONFIGURE_SIZE)?;
        }
        Body::ConfigureAck(m) => cap_size(m.size.as_ref(), CONFIGURE_ACK_SIZE)?,
        Body::Frame(m) => {
            cap_count(m.tiles.len(), MAX_TILES_PER_FRAME, "frame.tiles")?;
            for tile in &m.tiles {
                check_tile(tile)?;
            }
        }
        Body::CursorImage(m) => check_cursor(m)?,
        Body::PointerAxis(m) => {
            cap_steps(m.steps_x, "pointer_axis.steps_x")?;
            cap_steps(m.steps_y, "pointer_axis.steps_y")?;
        }
        Body::Key(m) => {
            if m.code.is_empty() || !m.code.is_ascii() || m.code.len() > MAX_KEY_CODE_BYTES {
                return Err(Violation::Limit("key.code"));
            }
        }
        Body::ClipboardSet(m) => cap_str(&m.text, MAX_CLIPBOARD_BYTES, "clipboard_set.text")?,
        Body::ClipboardText(m) => cap_str(&m.text, MAX_CLIPBOARD_BYTES, "clipboard_text.text")?,
        // Nothing to check: a bare id, plain numbers, or no fields at all.
        Body::FocusAsk(_)
        | Body::FrameAck(_)
        | Body::CursorGone(_)
        | Body::PointerMove(_)
        | Body::PointerButton(_)
        | Body::FocusNotify(_)
        | Body::BlurRelease(_)
        | Body::ClipboardAsk(_)
        | Body::CloseRequest(_) => {}
    }
    Ok(())
}

/// A SurfaceNew against its role, its sizes, its strings, its positioner and its scale.
fn check_surface_new(m: &SurfaceNew) -> Result<(), Violation> {
    closed::<Role>(m.role, "surface_new.role")?;
    cap_size(m.size.as_ref(), SURFACE_NEW_SIZE)?;
    cap_str(&m.title, MAX_TITLE_BYTES, "surface_new.title")?;
    cap_str(&m.app_id, MAX_APP_ID_BYTES, "surface_new.app_id")?;
    if let Some(positioner) = m.positioner.as_ref() {
        closed::<Anchor>(positioner.anchor, "surface_new.positioner.anchor")?;
        closed::<Anchor>(positioner.gravity, "surface_new.positioner.gravity")?;
        cap_size(positioner.size.as_ref(), POSITIONER_SIZE)?;
    }
    if m.scale_120ths == 0 {
        return Err(Violation::Limit("surface_new.scale_120ths"));
    }
    Ok(())
}

/// One tile of a Frame against its rows of the table.
fn check_tile(tile: &Tile) -> Result<(), Violation> {
    if let Some(rect) = tile.rect.as_ref() {
        cap_dim(rect.width, MAX_TILE_WIDTH, "tile.rect.width")?;
        cap_dim(rect.height, MAX_TILE_HEIGHT, "tile.rect.height")?;
    }
    if tile.codec == 0 {
        return Err(Violation::Limit("tile.codec"));
    }
    cap_bytes(&tile.data, MAX_TILE_BYTES, "tile.data")
}

/// A cursor image against its caps, and its bytes against its size: exactly
/// `width * height * 4`, the rule the TypeScript decoder enforces too.
fn check_cursor(m: &CursorImage) -> Result<(), Violation> {
    const FIELD: &str = "cursor_image.argb_premultiplied";
    cap_dim(m.width, MAX_CURSOR_WIDTH, "cursor_image.width")?;
    cap_dim(m.height, MAX_CURSOR_HEIGHT, "cursor_image.height")?;
    cap_bytes(&m.argb_premultiplied, MAX_CURSOR_BYTES, FIELD)?;
    // Both sides are at most 128 after the caps above, so the product cannot overflow.
    let expected = u64::from(m.width) * u64::from(m.height) * 4;
    if u64::try_from(m.argb_premultiplied.len()).ok() != Some(expected) {
        return Err(Violation::Limit(FIELD));
    }
    Ok(())
}

/// A closed enum: the value must be one the generated enum `E` names. prost stores enum
/// fields as plain `i32` and accepts any value on decode, so this is where v0's closed sets
/// are enforced, in both directions.
fn closed<E: TryFrom<i32>>(value: i32, field: &'static str) -> Result<(), Violation> {
    if E::try_from(value).is_err() {
        return Err(Violation::Protocol(field));
    }
    Ok(())
}

/// A wheel-step cap: at most [`MAX_POINTER_AXIS_STEPS`] either way. `unsigned_abs` keeps
/// `i32::MIN` in range.
fn cap_steps(value: i32, field: &'static str) -> Result<(), Violation> {
    if value.unsigned_abs() > MAX_POINTER_AXIS_STEPS {
        return Err(Violation::Limit(field));
    }
    Ok(())
}

/// A string cap: bytes, not characters.
fn cap_str(value: &str, max: usize, field: &'static str) -> Result<(), Violation> {
    cap_count(value.len(), max, field)
}

/// A bytes cap.
fn cap_bytes(value: &[u8], max: usize, field: &'static str) -> Result<(), Violation> {
    cap_count(value.len(), max, field)
}

/// A count cap.
fn cap_count(len: usize, max: usize, field: &'static str) -> Result<(), Violation> {
    if len > max {
        return Err(Violation::Limit(field));
    }
    Ok(())
}

/// A pixel-dimension cap.
fn cap_dim(value: u32, max: u32, field: &'static str) -> Result<(), Violation> {
    if value > max {
        return Err(Violation::Limit(field));
    }
    Ok(())
}

/// A surface-size cap. An absent size carries no dimension and cannot break one.
fn cap_size(size: Option<&Size>, fields: (&'static str, &'static str)) -> Result<(), Violation> {
    if let Some(size) = size {
        cap_dim(size.width, MAX_SURFACE_WIDTH, fields.0)?;
        cap_dim(size.height, MAX_SURFACE_HEIGHT, fields.1)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::limits::codec;

    fn envelope(body: Body) -> Envelope {
        Envelope { body: Some(body) }
    }

    /// Encodes without the limits gate, to craft bytes a hostile peer could send.
    fn raw_bytes(envelope: &Envelope) -> Vec<u8> {
        envelope.encode_to_vec()
    }

    // Both helpers return Option because the message fields they fill are Option<Message>;
    // wrapping here keeps every call site flat.
    #[allow(clippy::unnecessary_wraps)]
    fn size(width: u32, height: u32) -> Option<Size> {
        Some(Size { width, height })
    }

    #[allow(clippy::unnecessary_wraps)]
    fn rect(x: i32, y: i32, width: u32, height: u32) -> Option<Rect> {
        Some(Rect {
            x,
            y,
            width,
            height,
        })
    }

    fn tile(x: i32, y: i32, width: u32, height: u32, data: Vec<u8>) -> Tile {
        Tile {
            rect: rect(x, y, width, height),
            codec: codec::RAW,
            data,
        }
    }

    fn frame(surface_id: u32, sequence: u32, tiles: Vec<Tile>) -> Body {
        Body::Frame(Frame {
            surface_id,
            sequence,
            full_redraw: true,
            tiles,
        })
    }

    /// One valid Envelope per message kind, 25 in all.
    fn sample_kinds() -> Vec<Envelope> {
        let mut all = handshake_and_surface_samples();
        all.extend(frame_and_input_samples());
        all
    }

    /// Hello, HelloReply, Bye, ServerError, and the seven surface messages.
    fn handshake_and_surface_samples() -> Vec<Envelope> {
        vec![
            envelope(Body::Hello(Hello {
                protocol_version: u32::from(crate::PROTOCOL_VERSION),
                client_name: "client-0".into(),
                stream_token: b"token-0".to_vec(),
                codecs: vec![codec::RAW, codec::QOI],
                resume_serial: Some(5),
            })),
            envelope(Body::HelloReply(HelloReply {
                protocol_version: 0,
                session_id: "session-1".into(),
                max_frame_credits: 4,
                codecs: vec![codec::RAW],
                resumed: true,
                resume_serial: Some(9),
                resume_grace_ms: Some(10_000),
            })),
            envelope(Body::Bye(Bye {
                reason: ByeReason::ByePeerClosed as i32,
                text: "done".into(),
            })),
            envelope(Body::ServerError(ServerError {
                code: 4,
                text: "decode failure".into(),
            })),
            envelope(Body::SurfaceNew(SurfaceNew {
                surface_id: 1,
                role: Role::Toplevel as i32,
                parent_id: None,
                size: size(640, 480),
                title: "Main window".into(),
                app_id: "app.editor".into(),
                positioner: None,
                scale_120ths: 120,
            })),
            envelope(Body::SurfaceGone(SurfaceGone {
                surface_id: 1,
                reason: SurfaceGoneReason::GoneSessionEnd as i32,
            })),
            envelope(Body::SurfaceMetadata(SurfaceMetadata {
                surface_id: 1,
                title: Some("Renamed".into()),
                app_id: None,
                scale_120ths: Some(240),
            })),
            envelope(Body::FocusAsk(FocusAsk { surface_id: 2 })),
            envelope(Body::ResizeAsk(ResizeAsk {
                surface_id: 2,
                size: size(800, 600),
            })),
            envelope(Body::Configure(Configure {
                surface_id: 2,
                serial: 7,
                size: size(800, 600),
            })),
            envelope(Body::ConfigureAck(ConfigureAck {
                surface_id: 2,
                serial: 7,
                size: size(800, 599),
            })),
        ]
    }

    /// Frame, FrameAck, CursorImage, CursorGone, and the nine input messages.
    fn frame_and_input_samples() -> Vec<Envelope> {
        vec![
            envelope(frame(
                1,
                1,
                vec![tile(0, 0, 2, 2, vec![7; 16]), tile(2, 0, 2, 2, vec![9; 16])],
            )),
            envelope(Body::FrameAck(FrameAck {
                surface_id: 1,
                sequence: 1,
            })),
            envelope(Body::CursorImage(CursorImage {
                serial: 3,
                width: 2,
                height: 2,
                hotspot_x: 1,
                hotspot_y: 0,
                argb_premultiplied: vec![0x11; 16],
            })),
            envelope(Body::CursorGone(CursorGone {})),
            envelope(Body::PointerMove(PointerMove {
                surface_id: 1,
                x: 100,
                y: -5,
            })),
            envelope(Body::PointerButton(PointerButton {
                surface_id: 1,
                button: 1,
                pressed: true,
            })),
            envelope(Body::PointerAxis(PointerAxis {
                surface_id: 1,
                steps_x: 0,
                steps_y: -2,
            })),
            envelope(Body::Key(Key {
                keysym: 0x61,
                code: "KeyA".into(),
                pressed: true,
                modifiers: 1,
            })),
            envelope(Body::FocusNotify(FocusNotify { surface_id: 3 })),
            envelope(Body::BlurRelease(BlurRelease {})),
            envelope(Body::ClipboardSet(ClipboardSet {
                text: "hello world".into(),
            })),
            envelope(Body::ClipboardAsk(ClipboardAsk {})),
            envelope(Body::CloseRequest(CloseRequest { surface_id: 1 })),
            envelope(Body::ClipboardText(ClipboardText {
                text: "copied in the app".into(),
            })),
        ]
    }

    #[test]
    fn round_trips_every_message_kind() {
        assert_eq!(sample_kinds().len(), 25);
        for env in sample_kinds() {
            let bytes = encode_envelope(&env).expect("sample is valid");
            let back = decode_envelope(&bytes).expect("sample decodes");
            assert_eq!(back, env, "round trip changed the message");
            let again = encode_envelope(&back).expect("decoded sample is still valid");
            assert_eq!(again, bytes, "re-encode must be byte-identical");
        }
    }

    #[test]
    fn refuses_input_over_the_message_cap_before_parsing() {
        let oversized = vec![0u8; MAX_MESSAGE_BYTES + 1];
        assert!(matches!(
            decode_envelope(&oversized),
            Err(DecodeError::TooLarge)
        ));
        // The cap itself is inclusive: input exactly at it gets past the size gate, and the
        // pre-scan then refuses its first key (field number 0).
        let at_cap = vec![0u8; MAX_MESSAGE_BYTES];
        assert!(matches!(
            decode_envelope(&at_cap),
            Err(DecodeError::ProtocolViolation { field: "envelope" })
        ));
    }

    #[test]
    fn refuses_a_bodyless_envelope() {
        let bytes = raw_bytes(&Envelope { body: None });
        let err = decode_envelope(&bytes).expect_err("no body is a violation");
        assert!(matches!(err, DecodeError::UnknownMessage));
        assert!(matches!(
            validate_envelope(&Envelope { body: None }),
            Err(DecodeError::UnknownMessage)
        ));
        assert_eq!(
            encode_envelope(&Envelope { body: None }),
            Err(EncodeError::ProtocolViolation { field: "body" })
        );
    }

    /// One refused envelope: decode names `field`, encode refuses to emit it.
    fn expect_refused(env: &Envelope, field: &'static str) {
        let err = decode_envelope(&raw_bytes(env)).expect_err("must not decode");
        assert!(
            matches!(&err, DecodeError::LimitViolation { field: f } if *f == field),
            "decode: wrong violation for {field}: {err:?}"
        );
        assert_eq!(
            encode_envelope(env),
            Err(EncodeError::LimitViolation { field }),
            "encode: this side must refuse to emit it"
        );
        assert!(validate_envelope(env).is_err());
    }

    #[test]
    fn refuses_handshake_limit_violations() {
        expect_refused(
            &envelope(Body::Hello(Hello {
                client_name: "c".repeat(MAX_CLIENT_NAME_BYTES + 1),
                ..default_hello()
            })),
            "hello.client_name",
        );
        expect_refused(
            &envelope(Body::Hello(Hello {
                stream_token: vec![0; MAX_TOKEN_BYTES + 1],
                ..default_hello()
            })),
            "hello.stream_token",
        );
        expect_refused(
            &envelope(Body::Hello(Hello {
                codecs: vec![codec::RAW; MAX_CODECS_OFFERED + 1],
                ..default_hello()
            })),
            "hello.codecs",
        );
        expect_refused(
            &envelope(Body::HelloReply(HelloReply {
                session_id: "s".repeat(MAX_SESSION_ID_BYTES + 1),
                ..default_hello_reply()
            })),
            "hello_reply.session_id",
        );
        expect_refused(
            &envelope(Body::Bye(Bye {
                reason: ByeReason::ByePeerClosed as i32,
                text: "b".repeat(MAX_BYE_TEXT_BYTES + 1),
            })),
            "bye.text",
        );
        expect_refused(
            &envelope(Body::ServerError(ServerError {
                code: 1,
                text: "e".repeat(MAX_ERROR_TEXT_BYTES + 1),
            })),
            "server_error.text",
        );
    }

    #[test]
    fn refuses_surface_limit_violations() {
        expect_refused(
            &envelope(Body::SurfaceNew(SurfaceNew {
                title: "t".repeat(MAX_TITLE_BYTES + 1),
                ..default_surface_new()
            })),
            "surface_new.title",
        );
        expect_refused(
            &envelope(Body::SurfaceNew(SurfaceNew {
                app_id: "a".repeat(MAX_APP_ID_BYTES + 1),
                ..default_surface_new()
            })),
            "surface_new.app_id",
        );
        expect_refused(
            &envelope(Body::SurfaceNew(SurfaceNew {
                size: size(MAX_SURFACE_WIDTH + 1, 600),
                ..default_surface_new()
            })),
            "surface_new.size.width",
        );
        expect_refused(
            &envelope(Body::SurfaceNew(SurfaceNew {
                size: size(640, MAX_SURFACE_HEIGHT + 1),
                ..default_surface_new()
            })),
            "surface_new.size.height",
        );
        expect_refused(
            &envelope(Body::SurfaceNew(SurfaceNew {
                scale_120ths: 0,
                ..default_surface_new()
            })),
            "surface_new.scale_120ths",
        );
        expect_refused(
            &envelope(Body::SurfaceNew(SurfaceNew {
                positioner: Some(Positioner {
                    anchor_rect: rect(0, 0, 10, 10),
                    anchor: Anchor::BottomLeft as i32,
                    gravity: Anchor::TopRight as i32,
                    offset: Some(Point { x: -1, y: -6 }),
                    size: size(MAX_SURFACE_WIDTH + 1, 24),
                }),
                ..default_surface_new()
            })),
            "surface_new.positioner.size.width",
        );
        expect_refused(
            &envelope(Body::SurfaceMetadata(SurfaceMetadata {
                surface_id: 1,
                title: Some("t".repeat(MAX_TITLE_BYTES + 1)),
                app_id: None,
                scale_120ths: None,
            })),
            "surface_metadata.title",
        );
        expect_refused(
            &envelope(Body::SurfaceMetadata(SurfaceMetadata {
                surface_id: 1,
                title: None,
                app_id: None,
                scale_120ths: Some(0),
            })),
            "surface_metadata.scale_120ths",
        );
        expect_refused(
            &envelope(Body::ResizeAsk(ResizeAsk {
                surface_id: 2,
                size: size(MAX_SURFACE_WIDTH + 1, 600),
            })),
            "resize_ask.size.width",
        );
        expect_refused(
            &envelope(Body::Configure(Configure {
                surface_id: 2,
                serial: 1,
                size: size(600, MAX_SURFACE_HEIGHT + 1),
            })),
            "configure.size.height",
        );
        expect_refused(
            &envelope(Body::ConfigureAck(ConfigureAck {
                surface_id: 2,
                serial: 1,
                size: size(MAX_SURFACE_WIDTH + 1, 600),
            })),
            "configure_ack.size.width",
        );
    }

    #[test]
    fn refuses_frame_limit_violations() {
        expect_refused(
            &envelope(frame(
                1,
                1,
                vec![tile(0, 0, 1, 1, vec![0; 4]); MAX_TILES_PER_FRAME + 1],
            )),
            "frame.tiles",
        );
        expect_refused(
            &envelope(frame(
                1,
                1,
                vec![Tile {
                    rect: rect(0, 0, MAX_TILE_WIDTH + 1, 1),
                    codec: codec::RAW,
                    data: vec![0; 4],
                }],
            )),
            "tile.rect.width",
        );
        expect_refused(
            &envelope(frame(
                1,
                1,
                vec![Tile {
                    rect: rect(0, 0, 1, MAX_TILE_HEIGHT + 1),
                    codec: codec::RAW,
                    data: vec![0; 4],
                }],
            )),
            "tile.rect.height",
        );
        expect_refused(
            &envelope(frame(
                1,
                1,
                vec![Tile {
                    rect: rect(0, 0, 1, 1),
                    codec: 0,
                    data: vec![0; 4],
                }],
            )),
            "tile.codec",
        );
        expect_refused(
            &envelope(frame(
                1,
                1,
                vec![tile(0, 0, 1, 1, vec![0; MAX_TILE_BYTES + 1])],
            )),
            "tile.data",
        );
        expect_refused(
            &envelope(Body::CursorImage(CursorImage {
                width: MAX_CURSOR_WIDTH + 1,
                ..default_cursor()
            })),
            "cursor_image.width",
        );
        expect_refused(
            &envelope(Body::CursorImage(CursorImage {
                height: MAX_CURSOR_HEIGHT + 1,
                ..default_cursor()
            })),
            "cursor_image.height",
        );
        expect_refused(
            &envelope(Body::CursorImage(CursorImage {
                argb_premultiplied: vec![0; MAX_CURSOR_BYTES + 1],
                ..default_cursor()
            })),
            "cursor_image.argb_premultiplied",
        );
    }

    #[test]
    fn refuses_input_limit_violations() {
        expect_refused(
            &envelope(Body::Key(Key {
                keysym: 0x61,
                code: "c".repeat(MAX_KEY_CODE_BYTES + 1),
                pressed: true,
                modifiers: 0,
            })),
            "key.code",
        );
        expect_refused(
            &envelope(Body::Key(Key {
                keysym: 0x61,
                code: String::new(),
                pressed: true,
                modifiers: 0,
            })),
            "key.code",
        );
        expect_refused(
            &envelope(Body::Key(Key {
                keysym: 0x61,
                // "κeyA": four bytes, and not ASCII.
                code: "κeyA".into(),
                pressed: true,
                modifiers: 0,
            })),
            "key.code",
        );
        expect_refused(
            &envelope(Body::ClipboardSet(ClipboardSet {
                text: "x".repeat(MAX_CLIPBOARD_BYTES + 1),
            })),
            "clipboard_set.text",
        );
        expect_refused(
            &envelope(Body::ClipboardText(ClipboardText {
                text: "x".repeat(MAX_CLIPBOARD_BYTES + 1),
            })),
            "clipboard_text.text",
        );
    }

    #[test]
    fn accepts_messages_at_every_cap() {
        let at_caps = vec![
            envelope(Body::Hello(Hello {
                client_name: "c".repeat(MAX_CLIENT_NAME_BYTES),
                stream_token: vec![0; MAX_TOKEN_BYTES],
                codecs: vec![codec::QOI; MAX_CODECS_OFFERED],
                ..default_hello()
            })),
            envelope(Body::SurfaceNew(SurfaceNew {
                size: size(MAX_SURFACE_WIDTH, MAX_SURFACE_HEIGHT),
                title: "t".repeat(MAX_TITLE_BYTES),
                app_id: "a".repeat(MAX_APP_ID_BYTES),
                ..default_surface_new()
            })),
            envelope(frame(
                1,
                1,
                vec![
                    tile(
                        0,
                        0,
                        MAX_TILE_WIDTH,
                        MAX_TILE_HEIGHT,
                        vec![1; MAX_TILE_BYTES]
                    );
                    MAX_TILES_PER_FRAME
                ],
            )),
            envelope(Body::CursorImage(CursorImage {
                width: MAX_CURSOR_WIDTH,
                height: MAX_CURSOR_HEIGHT,
                argb_premultiplied: vec![2; MAX_CURSOR_BYTES],
                ..default_cursor()
            })),
            envelope(Body::Key(Key {
                keysym: 1,
                code: "c".repeat(MAX_KEY_CODE_BYTES),
                pressed: false,
                modifiers: 0,
            })),
            envelope(Body::ClipboardSet(ClipboardSet {
                text: "x".repeat(MAX_CLIPBOARD_BYTES),
            })),
            envelope(Body::ClipboardText(ClipboardText {
                text: "x".repeat(MAX_CLIPBOARD_BYTES),
            })),
        ];
        for env in at_caps {
            let bytes = encode_envelope(&env)
                .unwrap_or_else(|e| panic!("message at the cap must encode: {e}"));
            decode_envelope(&bytes).expect("message at the cap must decode");
        }
    }

    /// xorshift64* : a deterministic PRNG, no dependency needed. Truncation is the point: a
    /// PRNG hands out bits of its state.
    struct Rng(u64);

    #[allow(clippy::cast_possible_truncation)]
    impl Rng {
        fn next_u64(&mut self) -> u64 {
            let mut x = self.0;
            x ^= x >> 12;
            x ^= x << 25;
            x ^= x >> 27;
            self.0 = x;
            x.wrapping_mul(0x2545_f491_4f6c_dd1d)
        }

        fn byte(&mut self) -> u8 {
            (self.next_u64() >> 32) as u8
        }

        fn below(&mut self, n: usize) -> usize {
            (self.next_u64() % n as u64) as usize
        }
    }

    #[test]
    fn mutated_encodings_never_panic() {
        let corpus: Vec<Vec<u8>> = sample_kinds()
            .iter()
            .map(|env| encode_envelope(env).expect("sample encodes"))
            .collect();
        let mut rng = Rng(0x1234_5678_9abc_def0);
        let mut stayed_valid = 0usize;
        for _ in 0..10_000 {
            let base = &corpus[rng.below(corpus.len())];
            let mut bytes = base.clone();
            for _ in 0..=rng.below(4) {
                match rng.below(5) {
                    0 => {
                        let i = rng.below(bytes.len());
                        bytes[i] ^= 1 << rng.below(8);
                    }
                    1 => {
                        let i = rng.below(bytes.len());
                        bytes[i] = rng.byte();
                    }
                    2 => {
                        if bytes.len() > 1 {
                            bytes.truncate(1 + rng.below(bytes.len() - 1));
                        }
                    }
                    3 => {
                        for _ in 0..rng.below(16) {
                            bytes.push(rng.byte());
                        }
                    }
                    _ => {
                        let (a, b) = (rng.below(bytes.len()), rng.below(bytes.len()));
                        bytes.swap(a, b);
                    }
                }
            }
            // A mutation can land on another valid message; it must still re-encode.
            if let Ok(env) = decode_envelope(&bytes) {
                stayed_valid += 1;
                encode_envelope(&env).expect("decoded means valid, so encode works");
            }
        }
        assert!(
            stayed_valid > 0,
            "the corpus is valid; some mutation survives"
        );
    }

    fn default_hello() -> Hello {
        Hello {
            protocol_version: 0,
            client_name: "client-0".into(),
            stream_token: b"token-0".to_vec(),
            codecs: vec![codec::RAW],
            resume_serial: None,
        }
    }

    fn default_hello_reply() -> HelloReply {
        HelloReply {
            protocol_version: 0,
            session_id: "session-1".into(),
            max_frame_credits: 4,
            codecs: vec![codec::RAW],
            resumed: false,
            resume_serial: None,
            resume_grace_ms: None,
        }
    }

    fn default_surface_new() -> SurfaceNew {
        SurfaceNew {
            surface_id: 1,
            role: Role::Toplevel as i32,
            parent_id: None,
            size: size(640, 480),
            title: "Main window".into(),
            app_id: "app.editor".into(),
            positioner: None,
            scale_120ths: 120,
        }
    }

    fn default_cursor() -> CursorImage {
        CursorImage {
            serial: 1,
            width: 2,
            height: 2,
            hotspot_x: 0,
            hotspot_y: 0,
            argb_premultiplied: vec![0; 16],
        }
    }
}
